spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none              # 운영용은 none / 개발용은 update 또는 validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000

  sql:
    init:
      mode: never

  # 하위 설정 파일 병합
  config:
    import:
      - classpath:application-local.yml
      - classpath:application-jwt.yml
      - classpath:application-redis.yml

  profiles:
    active: local, redis                   # 실행 환경 (local, dev, prod 중 선택), Redis 프로필 활성화

# 공공 API, 외부 서비스 등 공통 설정
api:
  drug:
    service-url: "http://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList"
    service-key: ${DRUG_API_SERVICE_KEY}

google:
  cloud:
    vision:
      credentials:
        path: ${GOOGLE_APPLICATION_CREDENTIALS}

coolsms:
  api:
    key: ${COOLSMS_API_KEY}
    secret: ${COOLSMS_API_SECRET}