spring:
  datasource:
    url: {jdbc:mysql://localhost:3306/mediforme}
    username: {rds root user name}
    password: {rds user password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create # rds 연결 후, update로 변경
        default_batch_fetch_size: 1000