spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/mediforme
    username: root
    password: pjs507703!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
          default_batch_fetch_size: 1000
#    hibernate:
#      ddl:
#        auto: create # rds 연결 후, update로 변경
#      default_batch_fetch_size: 1000
  api:
    drug:
      service-url: "http://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList"
      service-key: "VXUr9ZgIWyu52aPoeEh4cIxqor7wMAObpey2FxGU4VHyJsFSZWGzWPgz4yYvPtbZPrfgWqemnwLpyYpIrB6xDQ%3D%3D"
  google:
    cloud:
      vision:
        credentials:
          path: ${GOOGLE_APPLICATION_CREDENTIALS}  # 환경 변수로 설정된 경로 사용
  coolsms:
    api:
      key: "NCSB6SRUZRUWBIBZ"
      secret: "JIP96XAXUCSNFFSDMQO4SNJRLB7VXL29"
  jwt:
    secret_key: "AbCdEfGhIjKlMnOpQrStUvWxYz1234567890+AbCdEfGhIjKlMnOpQrStUvWxYz===AbCdEfGhIjKlMnOpQrStUvWxYz1234567890+AbCdEfGhIjKlMnOpQrStUvWxYz==="