@host = http://localhost:8080
@accessToken = {{ACCESS_TOKEN}}


### (MR-1) 정상 이미지 업로드 -> 200 기대
POST {{host}}/medicine-recognitions
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="tylenol.jpeg"
Content-Type: image/jpeg

< ./samples/tylenol.jpeg
--boundary--


### (MR-2) 정상 이미지 업로드(다른 샘플) -> 200 기대
POST {{host}}/medicine-recognitions
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="wegovy.jpeg"
Content-Type: image/jpeg

< ./samples/wegovy.jpeg
--boundary--



### (MR-3) file 파라미터명 오류 -> 400 기대 (MissingServletRequestPartException 가능)
POST {{host}}/medicine-recognitions
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="wrong"; filename="tylenol.jpeg"
Content-Type: image/jpeg

< ./samples/tylenol.jpeg
--boundary--



### (MR-4) multipart 이지만 file 파트 자체가 없음 -> 400 기대
POST {{host}}/medicine-recognitions
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="dummy"
Content-Type: text/plain

hello
--boundary--



### (MR-5) Content-Type 잘못 보냄(JSON) -> 415 기대(Unsupported Media Type)
POST {{host}}/medicine-recognitions
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "file": "not-a-multipart"
}



### (MR-6) 빈 파일 업로드 -> 400 기대
### - 전역 예외처리 없으면 500으로 떨어질 수도 있으니 확인 포인트
POST {{host}}/medicine-recognitions
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="empty.bin"
Content-Type: application/octet-stream

< ./samples/empty.bin
--boundary--



### (MR-7) 이미지가 아닌 텍스트 파일 업로드 -> 400 또는 500 기대
POST {{host}}/medicine-recognitions
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="not-image.txt"
Content-Type: text/plain

< ./samples/not-image.txt
--boundary--



### (MR-8) 이미지지만 Content-Type을 일부러 text/plain으로 속임 -> 200/400 기대 (서버가 실데이터로 검증하는지 확인)
POST {{host}}/medicine-recognitions
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="tylenol.jpeg"
Content-Type: text/plain

< ./samples/tylenol.jpeg
--boundary--
