@host = http://localhost:8080
@accessToken = {{accessToken}}
@userId = 2
@userMedicineId = 7

### 0) 토큰이 유효한지 빠른 체크
GET {{host}}/user/test@test.com/name
Authorization: Bearer {{accessToken}}


### 1) 온보딩 등록 - 사용자 복용 약 등록
POST {{host}}/onboarding/register
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userLoginId": "test@test.com",
  "itemName": "타이레놀",
  "dosage": "1회 1정",
  "mealCd": 2,
  "timeCd": 1,
  "daysOfWeekCd": 1234567,
  "isAlarm": true
}


### 2) 온보딩 등록 (추가 약) - 약 2개 이상 등록 가능해야 함
POST {{host}}/onboarding/register
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userLoginId": "test@test.com",
  "itemName": "비타민C",
  "dosage": "1회 1포",
  "mealCd": 2,
  "timeCd": 1,
  "daysOfWeekCd": 1234567,
  "isAlarm": false
}


### 3) 사용자 복용 약 목록 조회 -  등록한 약 반환
GET {{host}}/onboarding/list/{{userId}}
Authorization: Bearer {{accessToken}}


### 4) 복용 약 삭제 (userMedicineId는 3번 응답에서 실제 값으로 교체)
DELETE {{host}}/onboarding/{{userMedicineId}}/delete?userId={{userId}}
Authorization: Bearer {{accessToken}}


### 5) 삭제 후 목록 재조회 (검증)
GET {{host}}/onboarding/list/{{userId}}
Authorization: Bearer {{accessToken}}




### 6) 인증 없이 접근 (보안 테스트) - (기대: HTTP 401 Unauthorized)
GET {{host}}/onboarding/list/{{userId}}



### 7) 다른 사용자 ID 접근 (권한 테스트) - 403 기대
# 다른 userId로 삭제 시도 → 서비스에서 UNAUTHORIZED_ACTION 터져야 정상
@otherUserId = 999
DELETE {{host}}/onboarding/{{userMedicineId}}/delete?userId={{otherUserId}}
Authorization: Bearer {{accessToken}}