@host = http://localhost:8080
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzY3NjkyMzU1LCJleHAiOjE3Njc2OTU5NTV9.1AxyHyh8rPMi6XrnyobOeGalIYk-D5UXCCpTzAkdXkw
@userId = 2


### 0) 인증 없이 접근 → 401 확인
GET {{host}}/status/user/{{userId}}


### 1) 상태 생성
POST {{host}}/status
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": {{userId}},
  "statusDate": "2026-01-06",
  "defaultStatusCd": 1,
  "drinkCd": 2,
  "conditionCd": 3,
  "statusMemo": "컨디션이 조금 안 좋아요"
}


### 2) 사용자 + 날짜로 상태 조회
GET {{host}}/status/user/{{userId}}/date/2026-01-06
Authorization: Bearer {{accessToken}}


### 3) 사용자 상태 전체 조회
GET {{host}}/status/user/{{userId}}
Authorization: Bearer {{accessToken}}


### 4) 주간 상태 요약 조회
GET {{host}}/status/user/{{userId}}/week-summary?startDate=2026-01-01&endDate=2026-01-07
Authorization: Bearer {{accessToken}}


### 5) 날짜 기준 상태 수정
PUT {{host}}/status/user/{{userId}}/date/2026-01-06
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": {{userId}},
  "statusDate": "2026-01-06",
  "defaultStatusCd": 2,
  "drinkCd": 1,
  "conditionCd": 2,
  "statusMemo": "수정된 상태 메모"
}


### 6) 상태 ID로 단건 조회 (관리자/디버깅용)
@statusId = 3
GET {{host}}/status/{{statusId}}
Authorization: Bearer {{accessToken}}


### 7) 상태 삭제
DELETE {{host}}/status/{{statusId}}
Authorization: Bearer {{accessToken}}


### 8) 삭제 후 재조회 → 404 기대
GET {{host}}/status/{{statusId}}
Authorization: Bearer {{accessToken}}



## 예외 / 보안 테스트
### 9) 필수값 누락 → 400
POST {{host}}/status
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": {{userId}},
  "statusDate": "2026-01-06"
}


### 10) 날짜 포맷 오류 → 400
GET {{host}}/status/user/{{userId}}/date/2026-99-99
Authorization: Bearer {{accessToken}}